name: 'Trigger Jenkins Job and Return Result'
description: 'I am used to trigger a Jenkins job and return the success/failure of the job run'
inputs:
  jenkins-url:  # URL of the jenkins server
    description: 'URL of the Jenkins server'
    required: true
  jenkins-job: # The name of the jenkins job to run
    description: 'The name of the jenkins job to run'
    required: true
  jenkins-basic-auth: # basic auth for jenkins
    description: 'basic auth for jenkins, can use token or password for second part. Store this in a secret for security'
    required: true
  poll-time: # how often to poll the jenkins server for results
    description: 'How often (seconds) to poll the jenkins server for results'
    required: false
    default: 10
  verbose: # true/false - turns on verbose logging
    description: 'true/false - turns on verbose logging'
    required: false
    default: false
  just-trigger: # true/false - just triggers and checks if started. Won't check further results. Can be used when status is checked in different job 
    description: 'true/false - turns on just trigger so you can track stages in different jobs'
    required: false
    default: false
  buildwithParameters: # true/false - just triggers and checks if started. Won't check further results. Can be used when status is checked in different job 
    description: 'true/false - turns on just trigger so you can track stages in different jobs'
    required: false
    default: false
  parameters: # parameters for build
    description: 'map of parameters: KEY=VALUE,KEY=VALUE. used when building with parameters'
    required: false
    default: ""

outputs:
  build-url:
    description: 'build url for jenkins job. is set only when just-trigger is true'
    value: ${{ steps.trigger-jenkins-job-using-api.outputs.build-url }}
  
runs:
  using: "composite"
  steps:
    - id: trigger-jenkins-job-using-api
      run: |
        #Parameters
        JENKINS_URL="${{ inputs.jenkins-url }}"
        JENKINS_JOB_NAME="${{ inputs.jenkins-job }}"
        JENKINS_TOKEN="${{ inputs.jenkins-basic-auth }}"
        POLL_TIME=${{ inputs.poll-time }}
        VERBOSE=${{ inputs.verbose }}
        JUST_TRIGGER=${{ inputs.just-trigger }}
        BUILD_WITH_PARAMETERS=${{ inputs.buildwithParameters }}
        PARAMETERS=${{ inupts.parameters }}

        #STEP 1: Trigger the Jenkins Job
        #This will return a 201 if the job is created, so we need to test for this
        #Generate Crumb value
        echo "Triggering Jenkins Job..."
        CRUMB=`curl -s -H "Authorization: Basic ${JENKINS_TOKEN}" $JENKINS_URL'/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'`
        if BUILD_WITH_PARAMETERS ; then 
          DATA_PARAMS="--data $(echo $PARAMETERS | sed 's/\,/ --data /g')"
          if [ -z $PARAMETERS ]; then
            DATA_PARAMS=""
          fi
          TRIGGERJOBHEADER=$(curl -I -s -X POST -H "Authorization: Basic ${JENKINS_TOKEN}"  -H "$CRUMB" $DATA_PARAMS "$JENKINS_URL"/job/"$JENKINS_JOB_NAME"/buildWithParameters)
        else
          TRIGGERJOBHEADER=$(curl -I -s -X POST -H "Authorization: Basic ${JENKINS_TOKEN}"  -H "$CRUMB" "$JENKINS_URL"/job/"$JENKINS_JOB_NAME"/build)
        fi

        if [[ $VERBOSE == true ]]; then
            echo "Results of Triggering The Job:"
            echo "--------------------------------------"
            echo "${TRIGGERJOBHEADER}"
            echo "--------------------------------------"
        fi

        #STEP 2: Did STEP 1 return a 201. If so, continue, if not, stop the script
        #Regex to get the queue URL
        regex="location:\s*(http.*\/queue\/item\/([0-9]+)\/)"
        #Does the returned value contain 201 Created
        if [[ "${TRIGGERJOBHEADER}" == *"201"* ]]; then
            echo "Job triggered successfully"
            echo "--------------------------------------"
        else
            echo "201 NOT FOUND. Exiting script with error"
            echo "--------------------------------------"
            exit 1
        fi

        #STEP 3: Get the queue location from TRIGGERJOBHEADER
        #Get the queue URL
        if [[ "${TRIGGERJOBHEADER}" =~ $regex ]]; then
            echo "Queue URL Found."
            echo "--------------------------------------"
            QUEUEURL=${BASH_REMATCH[1]} ;
            if [[ $VERBOSE == true ]]; then
              echo $QUEUEURL ; 
              echo "--------------------------------------"
            fi
        else 
            echo "Queue URL NOT FOUND. Exiting script with error"
            echo "--------------------------------------"
            exit 1 
          exit 1 
            exit 1 
        fi

        #STEP 4: Get the JobID and URL using the queue location
        echo "Retreiving Job URL..."
        #Sleep to ensure the job gets started. Sometimes Jenkins has a few seconds pause
        sleep 10
        BUILDJSON=$(curl -s -X GET -H "Authorization: Basic ${JENKINS_TOKEN}" "${QUEUEURL}/api/json?pretty=true")
        if [[ $VERBOSE == true ]]; then
            echo "BUILDJSON:"
            echo "--------------------------------------"
            echo $BUILDJSON | jq .
            echo "--------------------------------------"
        fi

        #regex_blocked_status="\"blocked\"\s*:\s*([a-z]+)"
        regex="\"blocked\"\s*:\s*([a-z]+).*\"executable\".*?\"number\"\s*:\s*([0-9]+).*?\"url\"\s*:\s*\"(.*?)\""
        if [[ $BUILDJSON =~ $regex ]]; then
            if [[ $VERBOSE == true ]]; then
                echo "blocked: " ${BASH_REMATCH[1]} ;
                echo "build number: " ${BASH_REMATCH[2]} ;
                echo "build URL: " ${BASH_REMATCH[3]} ;
                echo "--------------------------------------"
            fi
            echo "Job URL retrieved"
            echo "--------------------------------------"
            BUILD_URL=${BASH_REMATCH[3]};
            if [[ "${BASH_REMATCH[1]}" == "true" ]]; then
                echo "Build Blocked. Exiting script with error"
                echo "--------------------------------------"
                exit 1
            fi
        else
            echo "Build number/URL NOT FOUND. Exiting script with error"
            echo "--------------------------------------"
            exit 1 
          exit 1 
            exit 1 
        fi

        #At this point, we have the URL for the build job, so now we can query the status of the job until something happens

        #STEP 5: Using the Job URL, query the job until we get some sort of code returned (success, failure, etc) and take appropriate steps
        #Potential Values: https://javadoc.jenkins-ci.org/hudson/model/Result.html
        #SUCCESS - Build had no errors
        #UNSTABLE - Build had some errors but they were not fatal
        #FAILURE - Build had a fatal error
        #NOT_BUILT - Module was not build
        #ABORTED - Manually aborted
        #Short pause
        sleep 2
        echo "Query Build Job Status"
        echo "--------------------------------------"
        JOBSTATUSJSON=$(curl -s -X GET -H "Authorization: Basic ${JENKINS_TOKEN}" "${BUILD_URL}api/json?pretty=true")
        if [[ $VERBOSE == true ]]; then
            echo "JOBSTATUSJSON:"
            echo "--------------------------------------"
            echo $JOBSTATUSJSON | jq .
            echo "--------------------------------------"
        fi

        regex="\"building\"\s*:\s*([a-z]+).*?\"result\"\s*:\s*\"?([a-zA-Z]+)\"?."
        if [[ $JOBSTATUSJSON =~ $regex ]]; then
            if [[ $VERBOSE == true ]]; then
                echo "Job Status"
                echo "building: " ${BASH_REMATCH[1]} ;
                echo "result: " ${BASH_REMATCH[2]} ;
            fi
            BUILDING=${BASH_REMATCH[1]} ;
            RESULT=${BASH_REMATCH[2]} ;

            if [[ "$BUILDING" == "true" ]] && [[ "$JUST_TRIGGER" == true ]]; then 
                echo "::set-output name=build-url::${BUILD_URL}"
                echo "Job is running. build-url is set. Exiting process..."
                exit 0
            fi
        else
            echo "Build status NOT FOUND. Exiting script with error"
            echo "--------------------------------------"
            exit 1 
          exit 1 
            exit 1 
        fi
        
        LOG_LENGTH=0;

        while [ "$BUILDING" == "true" ]
        do 
            
            
            #WAIT POLL_TIME SECONDS
            # echo "pause for $POLL_TIME seconds"
            # echo "--------------------------------------"
                sleep $POLL_TIME
    
            #Get the status
            # echo "Query Build Job Status"
            # echo "--------------------------------------"
            JOBSTATUSJSON=$(curl -s -X GET -H "Authorization: Basic ${JENKINS_TOKEN}" "$BUILD_URL/api/json?pretty=true")

            LOG_TEXT=$(curl -i -s -X GET -H "Authorization: Basic ${JENKINS_TOKEN}" "${BUILD_URL}logText/progressiveText?start=${LOG_LENGTH}")
            LOG_REGEX="x-text-size:\s*([0-9]+)"
            if [[ $LOG_TEXT =~ $LOG_REGEX ]]; then
                LOG_LENGTH=${BASH_REMATCH[1]} ;
                # echo $LOG_LENGTH
                # echo "--------------------------------------"
                
            fi
            # just removing first 10 line because i cant seperate headers another way
            echo "$LOG_TEXT" | sed -e '1,10d'
            regex="\"building\"\s*:\s*([a-z]+).*?\"result\"\s*:\s*\"?([a-zA-Z]+)\"?."
            if [[ $JOBSTATUSJSON =~ $regex ]]; then
                if [[ $VERBOSE == true ]]; then
                echo "Job Status"
                echo "building: " ${BASH_REMATCH[1]} ;
                echo "result: " ${BASH_REMATCH[2]} ;
                fi
                BUILDING=${BASH_REMATCH[1]} ;
                RESULT=${BASH_REMATCH[2]} ;
            else
                echo "Build status NOT FOUND. Exiting script with error"
                echo "--------------------------------------"
                exit 1 
            fi
        done 
        #Once I reach here, building is false, so the job isn't running any longer
        #Therefor, we can check the result
        case $RESULT in
            SUCCESS)
                echo "Build completed successfully!"
                EXIT_CODE=0
                ;;
            *)
                echo "Build DID NOT COMPLETE successfully"
                EXIT_CODE=1
                ;;
        esac
        
        exit $EXIT_CODE
      shell: bash
branding:
  icon: 'arrow-down-circle'
  color: 'gray-dark'