name: Test Jenkins Action

on:
  workflow_dispatch:


jobs:

  testaction:
    
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      - id: testjenkinsaction
        uses: LongenesisLtd/trigger-jenkins-job@v1
        with:
          jenkins-url:  "${{ secrets.JENKINS_SERVER }}" # URL of the jenkins server
          jenkins-job: "mySampleApp" # The name of the jenkins job to run
          jenkins-basic-auth: "${{ secrets.JENKINS_TOKEN }}" # basic auth encodedd
          poll-time: 10 # how often to poll the jenkins server for results
          verbose: true # true/false - turns on extra logging
          just-trigger: true # true/false - turns on just trigger so you can track stages in different jobs
          buildwithParameters: true # true/false - jenkins pipeline using parameters
          parameters: "SECRET_ID=123-431,ENVIRONMENT=test" # jenkins pipeline parameters, currently just strings that you can pass in --data
      
